/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/env.d.ts` (hash: 1177c209bb457d419779798c493147d2)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
