// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from '../../../app.js'

export type PageName = 'Appointments/Index' | 'Appointments/New' | 'Appointments/Show' | 'Dashboard' | 'Events/Index' | 'FollowUps/Index' | 'Login' | 'Owners/Form' | 'Owners/Index' | 'Pets/Form' | 'Pets/Index' | 'Setup' | 'Users/Form' | 'Users/Index'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Appointments/Index': unknown
    'Appointments/New': unknown
    'Appointments/Show': unknown
    'Dashboard': unknown
    'Events/Index': unknown
    'FollowUps/Index': unknown
    'Login': unknown
    'Owners/Form': unknown
    'Owners/Index': unknown
    'Pets/Form': unknown
    'Pets/Index': unknown
    'Setup': unknown
    'Users/Form': unknown
    'Users/Index': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
