// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from '../../../app.js'

export type PageName = 'Dashboard' | 'Login' | 'Owners/Form' | 'Owners/Index' | 'Pets/Form' | 'Pets/Index' | 'Setup' | 'Users/Form' | 'Users/Index'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Dashboard': unknown
    'Login': unknown
    'Owners/Form': unknown
    'Owners/Index': unknown
    'Pets/Form': unknown
    'Pets/Index': unknown
    'Setup': unknown
    'Users/Form': unknown
    'Users/Index': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
