// AUTO-GENERATED by @hono/inertia/vite. Do not edit.
import type app from '../../../app.js'

export type PageName = 'Dashboard' | 'Login' | 'Setup'

declare module '@hono/inertia' {
  interface InertiaPages {
    'Dashboard': unknown
    'Login': unknown
    'Setup': unknown
  }
  interface AppRegistry {
    app: typeof app
  }
}

export type { PageProps } from '@hono/inertia'
